# Generated by Django 4.1 on 2023-10-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nome_categoria', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('Aço', 'AÇO'), ('Madeira', 'MADEIRA'), ('Metal', 'METAL')], max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fornecedores', models.CharField(choices=[('-', '-')], max_length=100)),
                ('descricao', models.CharField(max_length=600)),
            ],
        ),
    ]
