# Generated by Django 4.1 on 2023-10-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotografia',
        ),
    ]
